### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by JVanBuskirk** [belangeo/pyo-plug#2]
Hello,
  I sat down yesterday to start working on a plug in that does exactly this to find out you had just created one.  I would be happy to contribute if you have a To Do list.  I've created a vsti version with a midi keyboard underneath the code editor.  Just let me know if I can help.

**Comment by JVanBuskirk** [comment]
Excellent! I could send you the pull request for the vsti and keep it updated with your progress.  As I mentioned, I have only added MIDI and the keyboard GUI at this point.  I was thinking about creating sliders which could map to SigTo() objects.  This way you could automate controls in the DAW. 

The two biggest issues I see right now are the script resets when you close and reopen the interface (only tested in Reaper) and Reaper ignores the shift bar in the code editor.  Shift starts and stops playback.  Shift-space works.

I've been working on getting my Pyo/Juce Plugins to work on windows.  I was able to build without errors this week, but they would not run.  I look forward to seeing what you come up with.  My issue is I only learn enough programming to do what I need to do which leaves major gaps.  I should read a book one day.

**Comment by belangeo** [comment]
VSTi and keyboard GUI could be great to have! I'm not sure about the sliders, that would better fit in single-process plugins with their own interface. I'd like to focus on scripting for this one (and keep it as much simple as possible!).

I noticed some keyboard issues on MacOS, I will fix these as soon as possible (on linux, there is no problem).

I will take a look at building on windows in a few days...

**Comment by JVanBuskirk** [comment]
Excellent.  Looking forward checking it out right now.  As always, thank you for the help.  I have a class of 15 using Pyo right now.  I have another student starting to build Pyo plugins on Raspberry Pi.  They will be putting all of your work on embedded Pyo to use right away

**Comment by belangeo** [comment]
Nice, good news!
About the keyboard space and return key with Reaper on MacOS, I put a note in the README, it can't be handle on the JUCE side.
I also added 12 automatable parameters for each plugin (normalized between 0 and 1). There is no GUI, they can be used directly in the code with variables PARAM1 to PARAM12. PARAMx are SigTo objects.

**Comment by belangeo** [comment]
I've just pushed a first release (1.0.0). I'm closing this issue as everything here have been addressed.
